Update Jenkinsfile_AIP

diff --git a/Jenkinsfile_AIP b/Jenkinsfile_AIP
--- a/Jenkinsfile_AIP
+++ b/Jenkinsfile_AIP
@@ -1,5 +1,6 @@
 def propfile
-
+def allJob = env.JOB_NAME.tokenize('/') as String[];
+def projectName = allJob[2];
 pipeline {
 	agent {
     		kubernetes {
@@ -21,6 +22,8 @@ spec:
 """
 		}
 	}
+    
+  
 	stages {
 		stage('Build & Unit Test') {
 			steps {
@@ -31,7 +34,8 @@ spec:
 							echo 'use the command below when we switch to somslite source'
 							// sh 'for i in somslitebuild;do gradle --no-daemon -p ${i} clean build;done'
 							echo 'Add gradle clean and build for Somslite and comment this step' 
-							sh "mvn -Drevision=SomsLite-${env.GIT_BRANCH}-build-${env.BUILD_NUMBER}-SNAPSHOT -f sample-java-app/pom.xml clean package"
+							//sh 'mvn -f sample-java-app/pom.xml clean package'
+							sh "mvn -Drevision=${projectName}-${env.GIT_BRANCH}-build-${env.BUILD_NUMBER}-SNAPSHOT -f sample-java-app/pom.xml clean package"
 							propfile = readProperties(file: './project.properties')
 							if (propfile['javadoc'] == "true") {
 								sh 'mvn javadoc:aggregate'
@@ -44,22 +48,24 @@ spec:
 									exclusionPattern: '**/test*'
 								)
 							}
+							
 						}	
 					}
 				}
 			}
 		}
          stage('Code Quality') {
-	 	when { expression {propfile['code_quality'] == "true" }}
+	 when { expression {propfile['code_quality'] == "true" }}
 		steps {
 			container('gradle') {
 				withMaven(maven: 'MAVEN-3.6.3') {
-					withSonarQubeEnv(installationName: 'Sonarqube') {
+					withSonarQubeEnv(installationName: 'Sonarqube') 
+									{
 						echo 'I am executing code quality using sonarqube'
 						echo 'update the line below when we switch to actual somslite repo'
 						// sh 'gradle Sonarqube'
 						echo 'remove the line below when we switch to actual somslite repo'
-						sh "mvn -f sample-java-app/pom.xml -Dsonar.projectName=SOMSLITE_${env.GIT_BRANCH} -Dsonar.projectKey=SOMSLITE_sample sonar:sonar"
+						sh "mvn -Drevision=${projectName}-${env.GIT_BRANCH}-build-${env.BUILD_NUMBER}-SNAPSHOT -f sample-java-app/pom.xml -Dsonar.projectName=SomsLite_${BRANCH_NAME} -Dsonar.projectKey=SOMSLITE_sample sonar:sonar"
 				      		}
 						sleep(60)
 						timeout(time: 1, unit: 'MINUTES') 
@@ -72,31 +78,37 @@ spec:
 		}
 	
 	stage("Publish Package") {
-		when { expression {env.GIT_BRANCH == 'dev' || env.GIT_BRANCH == 'release'|| propfile['feature_deploy'] == "true" }}
+	// when { expression {env.GIT_BRANCH == 'dev' || env.GIT_BRANCH == 'release'|| propfile['feature_deploy'] == "true" }}
 		steps {
 			container('gradle') {
 				script {
-					withMaven(maven: 'MAVEN-3.6.3') {
-						echo 'I am pushing the artifact with unique name showing the branch from which it is generated, to Archiva'
-						echo 'Replace the next 4 lines to reflect the Somslite artifact and push it to archiva'
-						echo 'use the 4 lines below when we switch to actual somslite repo'
-						/* echo 'copying the jar and war files from the individual target directorrys and copying it to artifacts directory '
-						sh "mkdir -p $WORKSPACE/artifacts"
-						sh 'for i in somslitebuild;do cp -rp ${i}/dist/libs/* $WORKSPACE/artifacts/ ;done' 
-						echo 'create a tar file on the Jenkins server'
-						sh "cd $WORKSPACE/artifacts/ && tar -cvzf artifact.tar * && md5sum artifact.tar archiveArtifacts artifacts: 'artifacts/*.tar', fingerprint: true 
-						*/
-						echo 'remove the 3 lines below when we switch to actual somslite repo'
-						sh "mv sample-java-app/target/sample-0.0.1-SNAPSHOT.jar sample-java-app/target/sample-build_${BUILD_NUMBER}-branch_${env.GIT_BRANCH}.jar"
-						sh 'ls -lrt sample-java-app/target/'
-						sh "mvn clean deploy -Drevision=SomsLite-${env.GIT_BRANCH}-build-${env.BUILD_NUMBER}-SNAPSHOT -Dmaven.test.skip=true"
+					propfile = readProperties(file: './project.properties')
+					println("deploy:" + propfile['feature_deploy'])
+					
+						withMaven(maven: 'MAVEN-3.6.3') {
+							echo 'I am pushing the artifact with unique name showing the branch from which it is generated, to Archiva'
+							echo 'Replace the next 4 lines to reflect the Somslite artifact and push it to archiva'
+							echo 'use the 4 lines below when we switch to actual somslite repo'
+							/* echo 'copying the jar and war files from the individual target directorrys and copying it to artifacts directory '
+							sh "mkdir -p $WORKSPACE/artifacts"
+							sh 'for i in somslitebuild;do cp -rp ${i}/dist/libs/* $WORKSPACE/artifacts/ ;done' 
+							echo 'create a tar file on the Jenkins server'
+							sh "cd $WORKSPACE/artifacts/ && tar -cvzf artifact.tar * && md5sum artifact.tar archiveArtifacts artifacts: 'artifacts/*.tar', fingerprint: true 
+							*/
+							echo 'remove the 3 lines below when we switch to actual somslite repo'
+							sh 'cd sample-java-app/target/'
+							//sh "mv sample-java-app/target/sample-0.0.1-SNAPSHOT.jar sample-java-app/target/sample-build_${BUILD_NUMBER}-branch_${env.GIT_BRANCH}.jar"
+						        sh 'ls -lrt sample-java-app/target/'
+						sh "mvn clean deploy -Drevision=${projectName}-${env.GIT_BRANCH}-build-${env.BUILD_NUMBER}-SNAPSHOT -Dmaven.test.skip=true"
+						echo "Archiva successfully pushed"
+						
 					}
 				}
 			}
 		}
 	}
 	stage("Deploy") {
-	        when { expression {env.GIT_BRANCH == 'dev' || env.GIT_BRANCH == 'release'|| propfile['feature_deploy'] == "true" }}
+	        when { expression {env.GIT_BRANCH == 'origin/dev' || env.GIT_BRANCH == 'origin/release'|| propfile['feature_deploy'] == "true" }}
 		steps {
 				container('gradle') {
 					script {
@@ -105,11 +117,11 @@ spec:
 									USERNAME=propfile['USERNAME_FEATURE_DEPLOY']
 									HOSTS=propfile['HOSTS_FEATURE_DEPLOY']
 								}
-								if (env.GIT_BRANCH == 'dev' ) {
+								if (env.BRANCH_NAME == 'dev' ) {
 									USERNAME=propfile['USERNAME_DEV_DEPLOY']
 									HOSTS=propfile['HOSTS_DEV_DEPLOY']
 								}
-								if (env.GIT_BRANCH == 'release') {
+								if (env.BRANCH_NAME == 'release') {
 									USERNAME=propfile['USERNAME_RELEASE_DEPLOY']
 									HOSTS=propfile['HOSTS_RELEASE_DEPLOY']
 								}
@@ -141,90 +153,63 @@ spec:
 				}
 			}
 		}
-	stage('Post Deploy Tests') {
-			when { expression {env.GIT_BRANCH == 'dev' || env.GIT_BRANCH == 'release'|| propfile['feature_deploy'] == "true" }}
-			parallel {
-				stage('Smoke Test') {
-					steps {
-						container('gradle') {
-							script {
-									withMaven(maven: 'MAVEN-3.6.3') {
-										echo 'I am executing Smoke Test on target dev environment post deployment'
-										/*RESP=`curl -X GET "${bamboo.uri}/RequestsRunning" -H "accept: application/xml" -H "authorization: bearer lR0AA2qfq7v9Ry96vDAgqcer1GPVd5yStmv1_aJVFS43rk06EytB7WsS0_owoiXIgpOXmZVEfkY4ST0JwHtRBk7RH0QRaldWtQT8udC0VdimdGx38RddY2sGaeeF0t9Aflr5rh1Jc_EUfkNK8YrKVxQ6kxB05aCe46CD2fkognv7TiJATmht-ycUjEsd_oy8jH5EK9fmn9eL-wXavNTQcEdsUmFm3-2r3IJDzMK7XCa74qu353yOKLvVyZ1yYQBnc1_fY5GS1BDrFLUZprxpAS30lGEu-d_JTTOQ989UJtIEB3cZzDkIQzeqdYBGCsiDdjdHo2DC1FK2kVPyBITTbQ"`
-										echo "The response for current execution status is: $RESP"
-										if [ "$RESP" != "[]" ];
-										then
-										echo "There is a test executing currently in Worksoft. Hence, not proceeding with the execution of Worksoft test cases."
-										exit 1
-										else
-										echo "There are no tests executing right now. Hence, proceeding with Worksoft test execution"
-										fi
-										# To abort the request before attempting to re-run, uncomment and run below line.
-										# abort=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/Request/${bamboo.RequestID}/abort/)
-										guid=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "parameters: {TestEnv}{${bamboo.stage_name}}" -H "id: ${bamboo.RequestID}" ${bamboo.uri}/ExecuteRequest/ | tr -d \")
-										echo "The GUID is: $guid"
-										status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
-										echo "The status is: $status"
-										while [[ $status != *"Completed"* ]]
-										do
-										status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
-										echo "The status is: $status"
-										sleep 15
-										done
-										status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/)
-										echo "The status is: $status"
-										execstatus=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${bamboo.uri}/ExecutionStatus/ | awk -F':' '{print $3}' | tr -d \" | tr -d \})
-										echo "The exec status is: $execstatus"
-										if [[ $execstatus != *Passed* ]];
-										then
-										echo "Failed"
-										exit 1
-										else
-										echo "Passed"
-										exit
-										fi
-										exit */
-									}
-							}
-						}
-					}
+stage('Post Deploy Tests') {
+when { expression {env.GIT_BRANCH == 'dev' || env.GIT_BRANCH == 'release'|| propfile['feature_deploy'] == "true" }}
+		parallel {
+			stage('Smoke Test') {
+				steps {
+					echo "I am executing Smoke Test on target dev environment post deployment"
 				}
-				stage('Security Test') {
-					steps {
-						container('gradle') {
-							script {
-									withMaven(maven: 'MAVEN-3.6.3') {
-										echo 'I am running Security Test here'
-									}
-							}
-						}
-					}
-				}
+				/*RESP=`curl -X GET "${WORKSOFT_URI}/RequestsRunning" -H "accept: application/xml" -H "authorization: bearer lR0AA2qfq7v9Ry96vDAgqcer1GPVd5yStmv1_aJVFS43rk06EytB7WsS0_owoiXIgpOXmZVEfkY4ST0JwHtRBk7RH0QRaldWtQT8udC0VdimdGx38RddY2sGaeeF0t9Aflr5rh1Jc_EUfkNK8YrKVxQ6kxB05aCe46CD2fkognv7TiJATmht-ycUjEsd_oy8jH5EK9fmn9eL-wXavNTQcEdsUmFm3-2r3IJDzMK7XCa74qu353yOKLvVyZ1yYQBnc1_fY5GS1BDrFLUZprxpAS30lGEu-d_JTTOQ989UJtIEB3cZzDkIQzeqdYBGCsiDdjdHo2DC1FK2kVPyBITTbQ"`
+				echo "The response for current execution status is: $RESP"
+				if [ "$RESP" != "[]" ];
+				then
+				echo "There is a test executing currently in Worksoft. Hence, not proceeding with the execution of Worksoft test cases."
+				exit 1
+				else
+				echo "There are no tests executing right now. Hence, proceeding with Worksoft test execution"
+				fi
+				# To abort the request before attempting to re-run, uncomment and run below line.
+				# abort=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "id: ${REQUESTID}" ${WORKSOFT_URI}/Request/${REQUESTID}/abort/)
+				guid=$(curl -X PUT -H "Authorization: Bearer $token" -d "" -H "parameters: {TestEnv}{${STAGE_NAME}}" -H "id: ${REQUESTID}" ${WORKSOFT_URI}/ExecuteRequest/ | tr -d \")
+				echo "The GUID is: $guid"
+				status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${WORKSOFT_URI}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
+				echo "The status is: $status"
+				while [[ $status != *"Completed"* ]]
+				do
+				status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${WORKSOFT_URI}/ExecutionStatus/ | awk -F':' '{print $2}' | tr -d \" | tr -d \})
+				echo "The status is: $status"
+				sleep 15
+				done
+				status=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${WORKSOFT_URI}/ExecutionStatus/)
+				echo "The status is: $status"
+				execstatus=$(curl -X GET -H "Authorization: Bearer $token" -d "" -H "APIRequestID: $guid" ${WORKSOFT_URI}/ExecutionStatus/ | awk -F':' '{print $3}' | tr -d \" | tr -d \})
+				echo "The exec status is: $execstatus"
+				if [[ $execstatus != *Passed* ]];
+				then
+				echo "Failed"
+				exit 1
+				else
+				echo "Passed"
+				exit
+				fi
+				exit */
 			}
-		}    
+			stage('Security Test') {
+				steps {
+				  container('gradle') {
+					script {
+						 withMaven(maven: 'MAVEN-3.6.3') {
+							echo 'I am running Security Test here'
+						     }
+				              }
+			             }
+		               }
+		      }
+	      }  
 	}
- 	post {
-  		always {
-			script {
-				if (propfile['javadoc'] == "true") {
-					javadoc(javadocDir: "/$WORKSPACE/target/site/apidocs", keepAll: true)
-        			}
-		  	}
-	  	}
-    		failure {
-			/*mail bcc: '', 
-			 body: "<b>Example</b><br>\n<br>Project: ${env.JOB_NAME} <br>Build Number: ${env.BUILD_NUMBER} <br> URL de build: ${env.BUILD_URL}", 
-			 cc: '', 
-			 charset: 'UTF-8', 
-			 from: '', 
-			 mimeType: 'text/html', 
-			 replyTo: '', 
-			 subject: "ERROR CI: Project name -> ${env.JOB_NAME}", 
-			 to: "foo@foomail.com";*/
-			echo 'I am sending a notification with failure'
-    		}
-	  	success {
-		  	echo 'I am sending a notification with success'
-	  	}
-  	}
-}
+     
+  }
+		
+	
+  }
